override SOURCEROOT	= ../../
PROGRAMS 		= texsculpt 
OWN_LIBS 		= Graphics Components CGLA
LIBS			= ${GLUTLIBS} ${GLLIBS} ${WIN_SYS_LIBS} -lm -lexpat
CXXFLAGS 		= -DSOLUTION
include ${SOURCEROOT}/makefiles/application.mk
