override SOURCEROOT	= ../..
PROGRAMS 		= hwshade
OWN_LIBS 		= X3DSceneGraph Geometry Graphics CGLA
LIBS			= ${GLUTLIBS} ${GLLIBS} ${WIN_SYS_LIBS} -lm -lexpat
CXXFLAGS = -DSOLUTION1 -DSOLUTION2
include ${SOURCEROOT}/makefiles/application.mk
